plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // Selenium
//    implementation 'org.seleniumhq.selenium:selenium-java:4.8.3'
    implementation 'org.seleniumhq.selenium:selenium-java:4.20.0'

    // WebDriverManager
//    implementation 'io.github.bonigarcia:webdrivermanager:5.3.2'
    implementation 'io.github.bonigarcia:webdrivermanager:5.7.0'

    // Cucumber + TestNG
    testImplementation 'io.cucumber:cucumber-java:7.16.0'
    testImplementation 'io.cucumber:cucumber-testng:7.16.0'
    testImplementation 'org.testng:testng:7.8.0'

    // Utilities
    implementation 'commons-codec:commons-codec:1.15'
    implementation 'commons-io:commons-io:2.8.0'

    // DB (optional)
    implementation 'mysql:mysql-connector-java:8.0.33'
    implementation 'org.springframework:spring-jdbc:5.3.30'
    implementation 'org.apache.commons:commons-dbcp2:2.9.0'
}

// ✅ Custom task
tasks.register('runTests') {
    group = "verification"
    description = "Runs all tests"
    dependsOn test
}

// ✅ VERY IMPORTANT
test {
    useTestNG()

    testLogging {
        events "passed", "failed", "skipped", "standard_out"
        showStandardStreams = true
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}